apiVersion: "skaffold/v4beta13"
kind: Config

build:
  tagPolicy:
    sha256: {}


  artifacts:
    - image: ai-orchestration
      context: .
      docker:
        dockerfile: apps/ai-orchestration/dockerfile
      sync:
       infer:
        - "apps/ai-orchestration/src/**"

    - image: auth
      context: .
      docker:
        dockerfile: apps/auth/dockerfile
      sync:
        infer:
          - "apps/auth/src/**"
    
    - image: notification
      context: .
      docker:
        dockerfile: apps/notification/dockerfile
      sync:
        infer:
          - "apps/notification/src/**"  

    - image: agent
      context: .
      docker:
        dockerfile: apps/sandbox/agent/dockerfile
      sync:
        infer:
          - "apps/sandbox/agent/src/**"

    - image: sync-agent
      context: .
      docker:
        dockerfile: apps/sandbox/sync-agent/dockerfile      

    - image: router
      context: .
      docker:
        dockerfile: apps/sandbox/router/dockerfile
      sync:
        infer:
          - "apps/sandbox/router/src/**"
          
    - image: sandbox
      context: .
      docker:
        dockerfile: apps/sandbox/server/dockerfile
      sync:
        infer:
          - "apps/sandbox/server/src/**"
          
    - image: template
      context: .
      docker:
        dockerfile: apps/sandbox/template/dockerfile
      sync:
        infer:
          - "apps/sandbox/template/src/**"

manifests:
  rawYaml:
     - k8s/secret.yml
     
     - k8s/ai-deployment.yml
     - k8s/ai-service.yml

     - k8s/auth-deployment.yml
     - k8s/auth-service.yml

     - k8s/notification-deployment.yml
     - k8s/notification-service.yml

     - k8s/sandbox-deployment.yml
     - k8s/sandbox-service.yml

     - k8s/ingress.yml

     - k8s/router-deployment.yml
     - k8s/router-service.yml

     - k8s/rbac.yml

     
