apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  AUTH_MONGO_URL: mongodb://admin:changeme@localhost:27017/buildable/auth?authSource=admin
  SANDBOX_MONGO_URL: "mongodb://admin:changeme@localhost:27017/buildable/sandbox?authSource=admin"
  AI_MONGO_URL: "mongodb://admin:changeme@localhost:27017/buildable/ai?authSource=admin"
  REDIS_URL: "redis://localhost.docker.internal:6379"
  
---

apiVersion: v1
kind: Secret
metadata:
  name: google
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: "YOUR_CLIENT_ID"
  GOOGLE_CLIENT_SECRET: "YOUR_CLIENT_SECRET"
  GOOGLE_REFRESH_TOKEN: "YOUR_REFRESH_TOKEN"
  GOOGLE_ACCESS_TOKEN: "YOUR_ACCESS_TOKEN"
  EMAIL_USER: "YOUR_EMAIL_USER"
--- 

apiVersion: v1
kind: Secret
metadata:
  name: jwt
type: Opaque
stringData:
  JWT_SECRET: "YOUR_SECRET_KEY"

---

apiVersion: v1
kind: Secret
metadata:
  name: ai-secret
type: Opaque
stringData:
  MISTRALAI_API_KEY: "YOUR_MISTRAL_API_KEY"
  GOOGLE_GEMINI_KEY: "YOUR_GEMINI_KEY"
  ANTHROPIC_API_KEY: "YOUR_ANTHROPIC_API_KEY"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: port
stringData: 
    SANDBOX_PORT: "3000"
    ROUTER_PORT: "3000"
    AGENT_PORT: "3000"
    AUTH_PORT: "3000"
    AI_PORT: "3000"
---
